# Generated by Django 3.2.8 on 2021-10-26 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
    ]
